# Generated by Django 2.2.7 on 2019-11-28 03:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataxtask',
            name='scheduler',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='Scheduler', to='backend.DataXJobScheduler', verbose_name='作业任务'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DataXTaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='操作人名称')),
                ('operate_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='操作人ID')),
                ('create_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='创建人名称')),
                ('create_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('operate_time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, '未运行'), (1, '运行中'), (2, '已完成'), (3, '终止')], default=0, verbose_name='任务状态')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='结束时间')),
                ('duration', models.IntegerField(default=0, verbose_name='运行时长')),
                ('task', models.ManyToManyField(related_name='Task', to='backend.DataXTask', verbose_name='任务状态')),
            ],
            options={
                'verbose_name': '任务状态',
                'verbose_name_plural': '任务状态',
                'db_table': 'dx_taskstatus',
                'ordering': ['-create_time'],
            },
        ),
    ]
