# Generated by Django 2.2.7 on 2019-11-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20191128_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataxtask',
            name='from_character',
            field=models.CharField(blank=True, default='utf8', max_length=10, null=True, verbose_name='来源编码'),
        ),
        migrations.AlterField(
            model_name='dataxtask',
            name='from_columns',
            field=models.CharField(blank=True, default='*', max_length=1000, null=True, verbose_name='来源列'),
        ),
        migrations.AlterField(
            model_name='dataxtask',
            name='from_where',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='来源条件'),
        ),
        migrations.AlterField(
            model_name='dataxtask',
            name='name',
            field=models.CharField(help_text='此名称用于保存为json模板名称', max_length=256, verbose_name='任务名称'),
        ),
        migrations.AlterField(
            model_name='dataxtask',
            name='task_error_limit_percentage',
            field=models.FloatField(blank=True, default=0.02, null=True, verbose_name='错误记录百分比'),
        ),
        migrations.AlterField(
            model_name='dataxtask',
            name='task_error_limit_record',
            field=models.SmallIntegerField(blank=True, default=5, null=True, verbose_name='错误记录条数'),
        ),
        migrations.AlterField(
            model_name='dataxtask',
            name='task_speed_channel',
            field=models.SmallIntegerField(blank=True, default=5, null=True, verbose_name='速度'),
        ),
        migrations.AlterField(
            model_name='dataxtask',
            name='to_character',
            field=models.CharField(blank=True, default='utf8', max_length=10, null=True, verbose_name='目标编码'),
        ),
        migrations.AlterField(
            model_name='dataxtask',
            name='to_columns',
            field=models.CharField(blank=True, default='*', max_length=1000, null=True, verbose_name='目标列'),
        ),
        migrations.AlterField(
            model_name='dataxtask',
            name='to_post_sql',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='后置条件'),
        ),
        migrations.AlterField(
            model_name='dataxtask',
            name='to_pre_sql',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='前置条件'),
        ),
        migrations.AlterField(
            model_name='dataxtask',
            name='to_session',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='目标session'),
        ),
    ]
