# Generated by Django 2.2.7 on 2019-11-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20191128_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataxtaskstatus',
            name='task',
            field=models.ManyToManyField(null=True, related_name='Task', to='backend.DataXTask', verbose_name='任务状态'),
        ),
    ]
