# Generated by Django 2.2.7 on 2019-11-29 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20191128_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataxjobscheduler',
            name='deploy_state',
            field=models.PositiveSmallIntegerField(choices=[(0, '未部署'), (1, '已部署')], default=0, verbose_name='作业部署状态'),
        ),
        migrations.AddField(
            model_name='dataxjobscheduler',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='运行时长'),
        ),
        migrations.AddField(
            model_name='dataxjobscheduler',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作业结束时间'),
        ),
        migrations.AddField(
            model_name='dataxjobscheduler',
            name='hostname',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='执行作业机器名称'),
        ),
        migrations.AddField(
            model_name='dataxjobscheduler',
            name='ip',
            field=models.CharField(default='127.0.0.1', max_length=100, verbose_name='执行作业机器ip'),
        ),
        migrations.AddField(
            model_name='dataxjobscheduler',
            name='port',
            field=models.PositiveSmallIntegerField(default=9999, verbose_name='执行作业机器端口'),
        ),
        migrations.AddField(
            model_name='dataxjobscheduler',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作业开始时间'),
        ),
        migrations.AddField(
            model_name='dataxjobscheduler',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, '未运行'), (1, '运行中'), (2, '结束'), (3, '异常终止')], default=0, verbose_name='作业运行状态'),
        ),
    ]
