# Generated by Django 2.2.7 on 2019-11-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20191129_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataxjobscheduler',
            name='end_time',
            field=models.DateTimeField(blank=True, default='', null=True, verbose_name='作业结束时间'),
        ),
        migrations.AlterField(
            model_name='dataxjobscheduler',
            name='start_time',
            field=models.DateTimeField(blank=True, default='', null=True, verbose_name='作业开始时间'),
        ),
        migrations.AlterField(
            model_name='dataxtaskstatus',
            name='end_time',
            field=models.DateTimeField(blank=True, default='', null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='dataxtaskstatus',
            name='start_time',
            field=models.DateTimeField(blank=True, default='', null=True, verbose_name='开始时间'),
        ),
    ]
