# Generated by Django 3.0 on 2019-12-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20191129_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataxjobscheduler',
            name='hostname',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='作业机器名称'),
        ),
        migrations.AlterField(
            model_name='dataxjobscheduler',
            name='ip',
            field=models.CharField(default='127.0.0.1', max_length=100, verbose_name='作业机器ip'),
        ),
        migrations.AlterField(
            model_name='dataxjobscheduler',
            name='port',
            field=models.PositiveSmallIntegerField(default=9999, verbose_name='作业机器端口'),
        ),
    ]
